# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sctx < Formula
  desc "Structured Context CLI — scoped context for AI agents"
  homepage "https://sctx.dev"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gregology/sctx/releases/download/v0.1.8/sctx_0.1.8_darwin_amd64.tar.gz"
      sha256 "e15f44acc27805e9dfbed642a68d5c357e4b3cd237225ffe08b0b6b40a606f30"

      define_method(:install) do
        bin.install "sctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gregology/sctx/releases/download/v0.1.8/sctx_0.1.8_darwin_arm64.tar.gz"
      sha256 "8ad5d351d7db60c56ab925b3cf325a8edff3d2adfd94b85f41b276c04a9ebd4f"

      define_method(:install) do
        bin.install "sctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gregology/sctx/releases/download/v0.1.8/sctx_0.1.8_linux_amd64.tar.gz"
      sha256 "07abc2bc213305b34762bacbcda6119f463f39dcc10e208bde6e56630fc846bd"
      define_method(:install) do
        bin.install "sctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gregology/sctx/releases/download/v0.1.8/sctx_0.1.8_linux_arm64.tar.gz"
      sha256 "30c38a6124d067b87b52dcab4edf4040ed69d0d238f13e8ea62024a49e066b62"
      define_method(:install) do
        bin.install "sctx"
      end
    end
  end
end
