# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sctx < Formula
  desc "Structured Context CLI — scoped context for AI agents"
  homepage "https://sctx.dev"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gregology/sctx/releases/download/v0.1.5/sctx_0.1.5_darwin_amd64.tar.gz"
      sha256 "532693683d7907cff51e267d2024686311ae58f192ed716b57efdcb310617e79"

      define_method(:install) do
        bin.install "sctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gregology/sctx/releases/download/v0.1.5/sctx_0.1.5_darwin_arm64.tar.gz"
      sha256 "75bff7391a781229d20634d8189b4119640287560b45a2b56511dfd0a9b67d3f"

      define_method(:install) do
        bin.install "sctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gregology/sctx/releases/download/v0.1.5/sctx_0.1.5_linux_amd64.tar.gz"
      sha256 "873d477dc30ef91799d4c90614a66c5901617da52708e118dea8eeb41e49150e"
      define_method(:install) do
        bin.install "sctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gregology/sctx/releases/download/v0.1.5/sctx_0.1.5_linux_arm64.tar.gz"
      sha256 "1131e2bd04ee50b610b4981b32c9f91757e64818e3fc7079b0585f67281aca26"
      define_method(:install) do
        bin.install "sctx"
      end
    end
  end
end
